# Generated by Django 4.1.13 on 2024-08-23 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=1024)),
                ('title', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('MRP', models.IntegerField()),
                ('last_7_day_sale', models.IntegerField(blank=True, null=True)),
                ('fit', models.CharField(blank=True, max_length=255, null=True)),
                ('fabric', models.CharField(blank=True, max_length=255, null=True)),
                ('neck', models.CharField(blank=True, max_length=255, null=True)),
                ('sleeve', models.CharField(blank=True, max_length=255, null=True)),
                ('pattern', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=255)),
                ('sizes', models.JSONField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_skus', to='NoberoApp.product')),
            ],
        ),
    ]
